### PR TITLE
RSFFE-43 fix: add another constants / attributes to links

### LINKED ISSUE #140: RSSFE-43 fixes
Add constant to footer link
Add target="_blank" to links
Change object in lang localStorage item to smth better

### PR DESCRIPTION
**Pull request by besovadevka**
Added target="_blank" to links
Added new contants
 Close #140

### CODE REVIEW

File: src/appConstants/index.ts [hunk 1]
```diff
@@ -89,7 +89,11 @@ export const APP_NAVIGATION_LINKS = {
     isAlwaysVisible: true,
   },
 };
-export const LANGUAGES = [{ lang: 'English' }, { lang: 'Русский' }];
+
+export enum Langs {
```
Comment (manuminsk) [inline src/appConstants/index.ts:93]: Could you swap key/value pairs?

**Review by manuminsk — APPROVED** [review]
